/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package CustomView;

/**
 *
 * @author ngdun
 */
public class T_View extends javax.swing.JPanel {

    /**
     * Creates new form T_View
     */
    public T_View() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LogoStory = new javax.swing.JLabel();
        NameStory = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();

        setBackground(new java.awt.Color(255, 251, 199));
        setMaximumSize(new java.awt.Dimension(175, 275));
        setMinimumSize(new java.awt.Dimension(175, 275));
        setPreferredSize(new java.awt.Dimension(175, 275));

        LogoStory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        LogoStory.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/library.png"))); // NOI18N
        LogoStory.setMaximumSize(new java.awt.Dimension(151, 190));
        LogoStory.setMinimumSize(new java.awt.Dimension(151, 190));
        LogoStory.setPreferredSize(new java.awt.Dimension(151, 190));

        NameStory.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        NameStory.setText("Tên truyện");
        NameStory.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(LogoStory, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE)
            .addComponent(NameStory, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(LogoStory, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(NameStory, javax.swing.GroupLayout.DEFAULT_SIZE, 37, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogoStory;
    private javax.swing.JLabel NameStory;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
